# Autogenerated wrapper script for pylon_julia_wrapper_jll for x86_64-linux-gnu-cxx03-julia_version+1.6.0
export pylon_julia_wrapper

using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("pylon_julia_wrapper")
JLLWrappers.@declare_library_product(pylon_julia_wrapper, "libpylon_julia_wrapper.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        pylon_julia_wrapper,
        "lib/libpylon_julia_wrapper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
